export default {
  "login": "adonis-sampaio",
  "id": 25649455,
  "node_id": "MDQ6VXNlcjI1NjQ5NDU1",
  "avatar_url": "https://avatars.githubusercontent.com/u/25649455?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/adonis-sampaio",
  "html_url": "https://github.com/adonis-sampaio",
  "followers_url": "https://api.github.com/users/adonis-sampaio/followers",
  "following_url": "https://api.github.com/users/adonis-sampaio/following{/other_user}",
  "gists_url": "https://api.github.com/users/adonis-sampaio/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/adonis-sampaio/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/adonis-sampaio/subscriptions",
  "organizations_url": "https://api.github.com/users/adonis-sampaio/orgs",
  "repos_url": "https://api.github.com/users/adonis-sampaio/repos",
  "events_url": "https://api.github.com/users/adonis-sampaio/events{/privacy}",
  "received_events_url": "https://api.github.com/users/adonis-sampaio/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Adonis Sampaio",
  "company": null,
  "blog": "",
  "location": "Rio de Janeiroa",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 15,
  "public_gists": 0,
  "followers": 0,
  "following": 0,
  "created_at": "2017-02-08T23:01:58Z",
  "updated_at": "2021-01-23T23:54:26Z"
  }